export default {
	REGISTER_USER: 'REGISTER_USER',
	LOGIN_USER: 'LOGIN_USER',
	USER_LOADING: 'USER_LOADING',
	VERIFY_USER: 'VERIFY_USER',
	AUTH_ERROR: 'AUTH_ERROR',
	LOG_OUT: 'LOG_OUT',
	GET_VACATIONS: 'GET_VACATIONS',
	DELETE_VACATION: 'DELETE_VACATION',
	ADD_VACATION: 'ADD_VACATION',
	GET_CHART_DATA: 'GET_CHART_DATA',
	LOGOUT_USER: 'LOGOUT_USER',
	GET_LIKED_VACATIONS: 'GET_LIKED_VACATIONS',
	CLEAR_VACATIONS: 'CLEAR_VACATIONS'
};
