export default {
	REGISTER_USER: 'REGISTER_USER',
	LOGIN_USER: 'LOGIN_USER',
	USER_LOADING: 'USER_LOADING',
	VERIFY_USER: 'VERIFY_USER',
	AUTH_ERROR: 'AUTH_ERROR',
	LOG_OUT: 'LOG_OUT',
	GET_VACATIONS: 'GET_VACATIONS',
	DELETE_VACATION: 'DELETE_VACATION',
	ADD_VACATION: 'ADD_VACATION'
};
